module.exports = (app)=>{
    const mongoose = app.mongoose;
    const Schema = mongoose.Schema;
    const PlayerTotalSchema = new Schema({
        seas_id:{
            type:String,
        },
        season:{
            type:String,
        },
        player_id:{
            type:String
        },
        player:{
            type:String
        },
        pos:{
            type:String,
        },
        age:{
            type:String,
        },
        experience:{
            type:String
        },
        tm:{
            type:String
        },
        g:{
            type:String,
        },
        gs:{
            type:String,
        },
        mp:{
            type:String
        },
        fg:{
            type:String
        },
        fga:{
            type:String,
        },
        fg_percent:{
            type:String,
        },
        x3p:{
            type:String
        },
        x3pa:{
            type:String
        },
        x3p_percent:{
            type:String,
        },
        x2p:{
            type:String,
        },
        x2pa:{
            type:String
        },
        x2p_percent:{
            type:String
        },
        e_fg_percent:{
            type:String
        },
        ft:{
            type:String
        },
        fta:{
            type:String
        },
        ft_percent:{
            type:String
        },
        orb:{
            type:String
        },
        drb:{
            type:String
        },
        trb:{
            type:String
        },
        ast:{
            type:String
        },
        stl:{
            type:String
        },
        blk:{
            type:String
        },
        tov:{
            type:String
        },
        pf:{
            type:String
        },
        pts:{
            type:String
        },
        pf:{
            type:String
        },
    },{
        timestamps:{createdAt: 'created', updatedAt: 'updated'}
    })
    return mongoose.model("PlayerTotal",PlayerTotalSchema,"PlayerTotalSchema")
}